#!/usr/bin/bash
sudo perf record -a -g -e 'block:*' -e 'io_uring:*' -e 'iocost:*' -e 'filelock:*' -e 'syscalls:*io*' -p `./getpid $1` -- sleep 50
sudo perf script | FlameGraph/stackcollapse-perf.pl | FlameGraph/flamegraph.pl --color=io --title="File I/O Time Flame Graph" > io.svg